---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 02.02.2020 23:15
----todo-- поиск цели с самым большим дпс для каста способности [готово]
--flag 1 = союзник, 2 = враг
function GetMaxAttackUnit(unit,range,flag)
	local MaxAttackUnit=nil
	local p=GetOwningPlayer(unit)
	local x,y=GetUnitX(unit),GetUnitY(unit)
	local CurrentAttack=0
	local MaxAttack=2

	if range==nil then	range=1000	end
	if flag==nil then	flag=1	end

	local e--временный юнит
	GroupEnumUnitsInRange(perebor,x,y,range,null)
	while true do
		e = FirstOfGroup(perebor)
		if e == nil then break end
		if flag==1 then
			if IsUnitAlly(e,p) and UnitAlive(e) then
				--print(GetUnitName(e).." в переборе")
				CurrentAttack=BlzGetUnitBaseDamage(e,0)

				if MaxAttack<=CurrentAttack then
					MaxAttack=CurrentAttack
					MaxAttackUnit=e
				end
			end
		end
		GroupRemoveUnit(perebor,e)
	end
	if MaxAttackUnit==nil then
		--print("цель не определена")
	else
		--print(MaxAttack.." - максимальная атака у  -"..GetUnitName(MaxAttackUnit))
	end
	return MaxAttackUnit
end
-- поиск близжайшего врага
function GetNearblyEnemyUnit(unit,range)
	local enemy=nil
	local p=GetOwningPlayer(unit)
	local x=GetUnitX(unit)
	local y=GetUnitY(unit)
	local currange=0
	local minrange=range

	if range==nil then
		range=1000
		minrange=1000
	end

	local e--временный юнит
	GroupEnumUnitsInRange(perebor,x,y,range,null)
	while true do
		e = FirstOfGroup(perebor)
		if e == nil then break end

		if IsUnitEnemy(e,p) and IsUnitDeadBJ(e)==false  and GetUnitCurrentOrder(unit)~="attack" then
			--print(GetUnitName(e).." в переборе")
			currange=DistanceBetweenXY(x,y,GetUnitX(e),GetUnitY(e))
			if minrange>=currange then
				minrange=currange
				enemy=e
			end
		end
		GroupRemoveUnit(perebor,e)
	end
	if enemy==nil then
		--print("цель не определена")
	else
		--print(minrange.." -ближайший радиус юнита -"..GetUnitName(enemy))
	end
	return enemy
end
----союзники
----flag 1=без маны
runits={}
-- поиск блихжаейшего союзника с самым большим процентом потерянного хп, флаг 1 ищет случайного без маны
function GetNearblyAlluUnit(unit,range,flag)
	local enemy=nil
	local p=GetOwningPlayer(unit)
	local x=GetUnitX(unit)
	local y=GetUnitY(unit)
	local currange=0
	local minrange=1
	if range==nil then
		range=600
		minrange=1
	end
	local e--временный юнит
	local i=0
	GroupEnumUnitsInRange(perebor,x,y,range,null)
	while true do
		e = FirstOfGroup(perebor)
		if e == nil then break end
		if IsUnitAlly(e,p) and UnitAlive(e) and IsUnitType(e,UNIT_TYPE_HERO)==false and e~=unit then -- and GetUnitCurrentOrder(unit)~="attack" then
			if flag==1 then
				if GetUnitState(e,UNIT_STATE_MAX_MANA) > GetUnitState(e,UNIT_STATE_MANA)  and GetUnitState(e,UNIT_STATE_MAX_MANA) >=1 then
					currange=100-GetUnitStatePercent(e,UNIT_STATE_MANA,UNIT_STATE_MAX_MANA)
					i=i+1
					runits[i]=e
				end
			else
				currange=100-GetUnitStatePercent(e,UNIT_STATE_LIFE,UNIT_STATE_MAX_LIFE)
			end
			if minrange<=currange and (flag==nil or flag==0) then
				minrange=currange
				enemy=e
			end
		end
		GroupRemoveUnit(perebor,e)
	end
	if flag==1 then
		enemy=runits[GetRandomInt(1,i)]
		runits={}
	end
	return enemy
end
function CloneUnit(caster,target)
	CreateUnit(GetAlly(GetOwningPlayer(caster)), GetUnitTypeId(target), GetUnitX(caster), GetUnitY(caster), GetUnitFacing(caster))
end
