---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 02.02.2020 23:15
--todo-- поиск цели с самым большим дпс для каста способности [готово]
--flag 1 = союзник, 2 = враг
function GetMaxAttackUnit(unit,range,flag)
	local MaxAttackUnit=nil
	local p=GetOwningPlayer(unit)
	local x,y=GetUnitX(unit),GetUnitY(unit)
	local CurrentAttack=0
	local MaxAttack=2

	if range==nil then	range=1000	end
	if flag==nil then	flag=1	end

	local e--временный юнит
	GroupEnumUnitsInRange(perebor,x,y,range,null)
	while true do
		e = FirstOfGroup(perebor)
		if e == nil then break end
		if flag==1 then
			if IsUnitAlly(e,p) and UnitAlive(e) then
				--print(GetUnitName(e).." в переборе")
				CurrentAttack=BlzGetUnitBaseDamage(e,0)

				if MaxAttack<=CurrentAttack then
					MaxAttack=CurrentAttack
					MaxAttackUnit=e
				end
			end
		end
		GroupRemoveUnit(perebor,e)
	end
	if MaxAttackUnit==nil then
		--print("цель не определена")
	else
		--print(MaxAttack.." - максимальная атака у  -"..GetUnitName(MaxAttackUnit))
	end
	return MaxAttackUnit
end