---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 04.01.2020 23:10
---
do
	function InitDamage()
		local DamageTrigger = CreateTrigger()
		for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
			TriggerRegisterPlayerUnitEvent(DamageTrigger, Player(i), EVENT_PLAYER_UNIT_DAMAGING) -- До вычета брони
			TriggerRegisterPlayerUnitEvent(DamageTrigger, Player(i), EVENT_PLAYER_UNIT_DAMAGED) -- После вычета брони
		end
		TriggerAddAction(DamageTrigger, function()
			local damage     = GetEventDamage() -- число урона
			local damageType = BlzGetEventDamageType()
			if damage < 1 then return end

			local eventId         = GetHandleId(GetTriggerEventId())
			local isEventDamaging = eventId == GetHandleId(EVENT_PLAYER_UNIT_DAMAGING)
			local isEventDamaged  = eventId == GetHandleId(EVENT_PLAYER_UNIT_DAMAGED)

			local target          = GetTriggerUnit() -- тот кто получил урон
			local caster          = GetEventDamageSource() -- тот кто нанёс урон
			local casterOwner     = GetOwningPlayer(caster)

			if isEventDamaged then
				if GetUnitAbilityLevel(target,FourCC('B001'))>0 then--щит маны
					local shieldcaster
					local deadcaster=false
					--print("получен урон под щитом "..damage)
					BlzSetEventDamage(0)

					local e--временный юнит
					GroupEnumUnitsInRange(perebor,GetUnitX(target),GetUnitY(target),300,null)
					while true do
						e = FirstOfGroup(perebor)
						if e == nil then break end

						if GetUnitAbilityLevel(e,FourCC('A00K'))>0  then
							if UnitAlive(e) then
								shieldcaster=e
							else
								deadcaster=true
							end
						end
						GroupRemoveUnit(perebor,e)
					end
					if deadcaster then
						print("как бы кастер уже умер")
						--UnitRemoveAbility(target,FourCC('B001'))
					end
					local data=HandleData[GetHandleId(shieldcaster)]
					data.shieldhp=data.shieldhp-damage
				end--конец щита маны
				if GetUnitAbilityLevel(target,FourCC('B003'))>0 then-- водный клон прямой снаряд
					UnitRemoveAbility(target,FourCC('B003'))
					BlzSetEventDamage(0)
					print("попал в цель")
					--CasrArea(target,FourCC('A00N'),GetUnitX(target),GetUnitX(target),500,GetUnitX(caster),GetUnitY(caster))
					local dummy=CreateUnit(GetOwningPlayer(target), FourCC('e000'), GetUnitX(target),GetUnitY(target), 0)
					local data=HandleData[GetHandleId(dummy)]
					if (data==nil) then data = {} HandleData[GetHandleId(dummy)] = data end
					data.CloneUnitID=GetUnitTypeId(target)
					UnitAddAbility(dummy,FourCC('A00N'))
					Cast(dummy,0,0,caster)
					--IssueTargetOrder(dummy,"acidbomb",caster)

				end
				if  GetUnitAbilityLevel(target,FourCC('B004'))>0 then
					UnitRemoveAbility(target,FourCC('B004'))
					BlzSetEventDamage(0)
					local data=HandleData[GetHandleId(caster)]
					CreateUnitSimpleEffect(target,data.CloneUnitID,"")
					--TODO Вася, добавь эфект по желанию
				end
			end
		end)
	end
end