---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 03.02.2020 0:53
----todo-- сделать глобальное увеличение мана регина у героев на 0.3 раз в минуиту, и максимальное количество маны на 50 раз в минуту

function UnitAddMaxMana (unit,mana)
	BlzSetUnitMaxMana(unit,BlzGetUnitMaxMana(unit)+mana)
end

function UpHero()
	TimerStart(CreateTimer(), 60, true, function()
		local e--временный юнит
		local MaxManaBonus=50
		local ManaRegenBonus=1
		GroupEnumUnitsInRect(perebor,bj_mapInitialPlayableArea,nil)
		while true do
			e = FirstOfGroup(perebor)
			if e == nil then break end
			--print(GetUnitName(e).." в переборе")
			if IsUnitType(e,UNIT_TYPE_HERO)  then -- and GetUnitCurrentOrder(unit)~="attack" then
				--print("приорст характеристик для "..GetUnitName(e))
				UnitAddMaxMana(e,MaxManaBonus)
				UnitAddBonus(e,7,ManaRegenBonus)
				--FIXME не работает в 132 патче, 03.02.2020 ждём фикса
				--UNIT_RF_MANA_REGENERATION
			end
			GroupRemoveUnit(perebor,e)
		end
	end)
end